### ISSUE TITLE
Criar função para retornar intervalo de confiança a partir de amostra de métricas de performance

### ISSUE THREAD

**Issue by karlvmsousa** [mmp-s/mining-project#17]
parâmetros: acurácias e nível de significância (alpha)

**Comment by mmp-s** [comment]
https://machinelearningmastery.com/statistical-significance-tests-for-comparing-machine-learning-algorithms/

Baseado neste artigo acredito que deveríamos utilizar o teste de Wilcoxon.

"We therefore recommend using the Wilcoxon test, unless the t-test assumptions are met, either because we have many data sets or because we have reasons to believe that the measure of performance across data sets is distributed normally."

**Comment by karlvmsousa** [comment]
Mas nesse caso são coisas complementares que podem ser feitas. No doc do projeto ele pede pra apresentar o desvio médio e desvio padrão da acurácia (n acho uma boa métrica no nosso caso de base desbalanceada...) e o box plot desses valores. Além disso o prof. também pediu pra fazer um teste de significância estatística pra realmente dizer que as performances são diferentes dos classificadores.

**Comment by karlvmsousa** [comment]
Mas no caso do Wilcoxon, até onde sei ele é feito somente de forma pareada, comparando de 2 em 2 modelos.
